# -*- coding: utf-8 -*-
"""FAQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X65C-mBf-kUirzHbYOLBM8m7gcc8mK58
"""

import streamlit as st

st.title("Frequently Asked Questions")
faq_expander = st.expander("General Questions", expander = true)
